// Platform Digital Blueprint — the authoritative ownership matrix for Interplanetary Fund.
// One capability, one owner. Systems interact only via APIs, the Event Bus,
// the Workflow Engine, and shared Base44 platform services.

export const operatingSystems = [
  {
    id: "constitution",
    prompt: 1,
    name: "Platform Constitution",
    role: "Global standards, architecture, security & accessibility baseline.",
    owns: ["Engineering standards", "Event Bus definition", "Workflow standards", "Feature flags", "Localization", "Design system"],
    neverOwns: ["Any business logic"],
    entities: [],
    publishes: [],
    consumes: [],
    dependsOn: [],
  },
  {
    id: "identity",
    prompt: 2,
    name: "Universal Identity Platform",
    role: "The single source of truth for who someone is and what they may do.",
    owns: ["Users", "Authentication", "Roles & permissions", "Profiles", "Sessions", "Consent & privacy", "Preferences"],
    neverOwns: ["Campaigns", "Donations", "Communities", "Grants", "Analytics"],
    entities: ["User"],
    publishes: ["UserRegistered", "UserRoleChanged"],
    consumes: [],
    dependsOn: ["Platform Foundation"],
  },
  {
    id: "campaign",
    prompt: 3,
    name: "Campaign Operating System",
    role: "Owns the full campaign lifecycle from draft to completion.",
    owns: ["Campaign creation & editing", "Goals", "Media", "Milestones", "Updates", "Campaign status"],
    neverOwns: ["User accounts", "Payment processing", "Communication delivery"],
    entities: ["Campaign", "CampaignUpdate"],
    publishes: ["CampaignCreated", "CampaignPublished", "CampaignMilestoneReached"],
    consumes: ["DonationCompleted", "GrantAwarded"],
    dependsOn: ["Universal Identity Platform"],
  },
  {
    id: "financial",
    prompt: 4,
    name: "Donation & Financial OS",
    role: "Every monetary transaction on the platform originates here.",
    owns: ["Donations", "Payments & refunds", "Recurring giving", "Tax receipts", "Financial reporting", "Grant disbursement records"],
    neverOwns: ["Campaign logic", "Identity", "Communications"],
    entities: ["Donation"],
    publishes: ["DonationCompleted", "RecurringGiftCancelled"],
    consumes: ["CampaignPublished"],
    dependsOn: ["Universal Identity Platform", "Campaign Operating System"],
  },
  {
    id: "communications",
    prompt: 5,
    name: "Communications & Engagement OS",
    role: "Every outbound message flows through this single pipeline.",
    owns: ["Email delivery", "In-app messaging", "Templates", "Audience segments", "Notification preferences", "Delivery analytics"],
    neverOwns: ["Campaign content authorship", "Donation processing", "Identity"],
    entities: ["Message", "Notification"],
    publishes: ["MessageSent", "NotificationDelivered"],
    consumes: ["DonationCompleted", "CampaignMilestoneReached", "GrantAwarded"],
    dependsOn: ["Universal Identity Platform"],
  },
  {
    id: "mission",
    prompt: 6,
    name: "Central Intelligence (Mission Control)",
    role: "Mission Control thinks; other operating systems execute.",
    owns: ["AI agents", "Recommendations", "Predictions", "Opportunity discovery", "Strategic briefings", "Growth plans"],
    neverOwns: ["Infrastructure", "Financial processing", "Identity", "Delivery", "Administrative analytics"],
    entities: ["Recommendation", "Opportunity", "MissionBrief"],
    publishes: ["RecommendationCreated", "RecommendationAccepted"],
    consumes: ["CampaignCreated", "DonationCompleted", "CommunityCreated", "OpportunityPublished"],
    dependsOn: ["All domain operating systems"],
  },
  {
    id: "community",
    prompt: 7,
    name: "Community & Network OS",
    role: "Communities, collaboration and volunteer networks.",
    owns: ["Communities", "Membership", "Discussions", "Volunteer opportunities", "Community governance & moderation"],
    neverOwns: ["Identity", "Campaign management", "Donations", "Institution management"],
    entities: ["Community", "CommunityMember", "DiscussionPost", "DiscussionReply", "VolunteerOpportunity", "VolunteerSignup"],
    publishes: ["CommunityCreated", "VolunteerJoined", "DiscussionPosted"],
    consumes: ["UserRegistered"],
    dependsOn: ["Universal Identity Platform"],
  },
  {
    id: "institution",
    prompt: 8,
    name: "Institutional Partnership OS",
    role: "Businesses, foundations, grant programs and partnerships.",
    owns: ["Institution profiles", "Verification", "Opportunity publishing", "Grant lifecycle", "Partnership agreements"],
    neverOwns: ["Identity", "Campaign logic", "Payment processing", "Analytics"],
    entities: ["Institution", "InstitutionOpportunity", "GrantApplication"],
    publishes: ["OpportunityPublished", "GrantApplicationSubmitted", "GrantAwarded"],
    consumes: ["CampaignCreated", "CommunityCreated"],
    dependsOn: ["Universal Identity Platform", "Campaign Operating System", "Community & Network OS"],
  },
  {
    id: "intelligence",
    prompt: 9,
    name: "Platform Intelligence OS",
    role: "Observes every operating system. Measures and reports; never mutates operational data.",
    owns: ["Analytics", "Dashboards", "Executive reports", "KPIs", "Forecasting", "Executive alerts"],
    neverOwns: ["Any operational business logic"],
    entities: ["ExecutiveReport"],
    publishes: ["ExecutiveReportGenerated", "ExecutiveAlertRaised"],
    consumes: ["All platform events"],
    dependsOn: ["All operating systems"],
  },
  {
    id: "foundation",
    prompt: 10,
    name: "Infrastructure & Evolution OS",
    role: "Powers the platform. Contains no business logic.",
    owns: ["Service registry", "Configuration & feature flags", "Audit timeline", "Knowledge repository", "Health monitoring", "This blueprint"],
    neverOwns: ["Campaigns", "Donations", "Communities", "Institutions", "AI decisions"],
    entities: ["FeatureFlag", "PlatformEvent", "KnowledgeArticle"],
    publishes: ["ConfigurationChanged", "HealthCheckExecuted", "KnowledgePublished"],
    consumes: [],
    dependsOn: ["Base44 managed infrastructure"],
  },
];

export const architecturalRules = [
  "One capability, one authoritative owner — never duplicate ownership.",
  "No direct cross-system data access: everything flows through APIs, the Event Bus, or the Workflow Engine.",
  "Every operating system must remain independently replaceable.",
  "Mission Control recommends; it never bypasses permissions or executes without approval.",
  "Platform Intelligence measures and reports; it never changes operational data.",
  "Platform Foundation provides technical capability only; it never contains business logic.",
];

export const managedByBase44 = [
  "Hosting & global delivery",
  "Database & storage",
  "Authentication infrastructure",
  "Deployments & rollback",
  "Backups & disaster recovery",
  "Scaling & monitoring",
  "Secrets management",
];